Update xray-install
цветовые решения

diff --git a/xray-install b/xray-install
--- a/xray-install
+++ b/xray-install
@@ -1,8 +1,7 @@
 #!/bin/bash
 
 
-
-echo -e "\033[1;33mПроверяем готовность сервера...\033[0m"
+#echo -e "\033[1;33mПроверяем готовность сервера...\033[0m"
 printf '\033[1;33m%s\033[0m\n' "Проверяем готовность сервера..."
 
 if command -v cloud-init >/dev/null 2>&1; then
@@ -14,32 +13,38 @@ if command -v cloud-init >/dev/null 2>&1; then
     fi
 
     if echo "$cloud_status" | grep -q "status: error"; then
-      echo "Ошибка: cloud-init завершился с ошибкой" >&2
+      #echo "Ошибка: cloud-init завершился с ошибкой" >&2
+      printf '\033[0;31m%s\033[0m\n' "Ошибка: cloud-init завершился с ошибкой" >&2
       exit 1
     fi
 
-    echo "Ждём завершения cloud-init..."
+    #echo "Ждём завершения cloud-init..."
+    printf '\033[1;33m%s\033[0m\n' "Ждём завершения cloud-init..."
     sleep 3
   done
 fi
 
 while pgrep -x apt >/dev/null || pgrep -x apt-get >/dev/null || pgrep -x dpkg >/dev/null || pgrep -x unattended-upgrade >/dev/null; do
-  echo "Ждём освобождения apt/dpkg..."
+  #echo "Ждём освобождения apt/dpkg..."
+  printf '\033[1;33m%s\033[0m\n' "Ждём освобождения apt/dpkg..."
   sleep 3
 done
 
 
 
-echo "Сервер готов к установке"
+#echo "Сервер готов к установке"
+printf '\033[0;32m%s\033[0m\n' "Сервер готов к установке"
 
 set -e
 export DEBIAN_FRONTEND=noninteractive
 if [[ $EUID -ne 0 ]]; then
-  echo "Ошибка: запустите скрипт от root" >&2
+  #echo "Ошибка: запустите скрипт от root" >&2
+  printf '\033[0;31m%s\033[0m\n' "Ошибка: запустите скрипт от root" >&2
   exit 1
 fi
 if ! command -v apt >/dev/null 2>&1; then
-  echo "Ошибка: пакетный менеджер apt не найден" >&2
+  #echo "Ошибка: пакетный менеджер apt не найден" >&2
+  printf '\033[0;31m%s\033[0m\n' "Ошибка: пакетный менеджер apt не найден" >&2
   exit 1
 fi
 apt update
@@ -47,20 +52,24 @@ apt install -y qrencode curl jq
 
 
 
-echo "==> Базовая защита сервера"
+#echo "==> Базовая защита сервера"
+printf '\033[0;36m%s\033[0m\n' "===> Активирую Базовую защиту сервера <==="
 
 # Смена пароля root
-echo "==> Сначала смените пароль root"
+#echo "==> Сначала смените пароль root"
+printf '\033[1;33m%s\033[0m\n' "===> Для защиты необходимо сменить пароль root <==="
 passwd root
 
 # Установка UFW и Fail2Ban
-echo "==> Установка UFW и Fail2Ban"
+#echo "==> Установка UFW и Fail2Ban"
+printf '\033[0;36m%s\033[0m\n' "===> Активирую защиту UFW и Fail2Ban <==="
 apt update
 apt install -y ufw fail2ban
 
 # Настройка UFW
 # ВАЖНО: сначала разрешаем SSH, потом включаем firewall
-echo "==> Настройка UFW"
+#echo "==> Настройка UFW"
+printf '\033[1;33m%s\033[0m\n' "===> Настраиваю UFW <==="
 ufw default deny incoming
 ufw default allow outgoing
 ufw allow OpenSSH
@@ -69,7 +78,8 @@ ufw --force enable
 
 # Настройка Fail2Ban
 # Правильно класть настройки в jail.d/*.local
-echo "==> Настройка Fail2Ban"
+#echo "==> Настройка Fail2Ban"
+printf '\033[1;33m%s\033[0m\n' "===> Настраиваю Fail2Ban <==="
 mkdir -p /etc/fail2ban/jail.d
 
 cat > /etc/fail2ban/jail.d/sshd.local <<'EOF'
@@ -96,11 +106,13 @@ echo "Fail2Ban:"
 fail2ban-client status sshd || systemctl status fail2ban --no-pager -l
 
 # Бэкап SSH-конфига
-echo "==> Резервная копия sshd_config"
+#echo "==> Резервная копия sshd_config"
+printf '\033[1;33m%s\033[0m\n' "===> Делаю Резервную копию sshd_config <==="
 cp /etc/ssh/sshd_config /etc/ssh/sshd_config.bak
 
 # Усиление SSH, НО парольный вход оставляем
-echo "==> Усиление SSH"
+#echo "==> Усиление SSH"
+printf '\033[1;33m%s\033[0m\n' "===> Делаю Усиление SSH <==="
 
 # Разрешить вход root по SSH
 if grep -qE '^[#[:space:]]*PermitRootLogin' /etc/ssh/sshd_config; then
@@ -145,7 +157,8 @@ else
 fi
 
 # Проверка и перезапуск SSH
-echo "==> Проверка sshd_config"
+#echo "==> Проверка sshd_config"
+printf '\033[1;33m%s\033[0m\n' "===> Проверяю sshd_config <==="
 if sshd -t; then
     systemctl restart ssh || systemctl restart sshd
 else
@@ -156,7 +169,8 @@ else
 fi
 
 echo ""
-echo "==> Базовая защита включена"
+#echo "==> Базовая защита включена"
+printf '\033[0;32m%s\033[0m\n' "===> Базовая защита активированна <==="
 echo "UFW:"
 ufw status verbose
 
